import 'package:http/http.dart' as http;
import 'dart:convert';

const  GOOGLE_API_KEY = 'YOUR KEY HERE';

//google static map api doc -> https://developers.google.com/maps/documentation/maps-static/overview
class LocationHelper{
  static String generateLocationPreviewImage({double latitude,double longitude}){
    //satic maps snapshot
    //return url to such an image which is dynamically generated by Google based on the coordinates pair
    return 'https://maps.googleapis.com/maps/api/staticmap?center=&$latitude,$longitude&zoom=16&size=600x300&maptype=roadmap&markers=color:red%7Clabel:A%7C$latitude,$longitude&key=$GOOGLE_API_KEY';
  }

  //turn LatLng location to human readable address
  //used in great_places.dart provider
  static Future<String> getPlaceAddress(double lat,double lng) async{
    //google has another API which gives us back a human readable address
    //Geocoding API -> https://developers.google.com/maps/documentation/geocoding/overview?_ga=2.239757003.954720743.1624005325-248812793.1624005325&_gac=1.51662427.1624012075.CjwKCAjwiLGGBhAqEiwAgq3q_maOa4EHbwzuD6xw-rzfzTaoXqLHL_TqYOiGa7W3LYMcHTTOfVtPcxoC4NkQAvD_BwE
    final url = Uri.parse('https://maps.googleapis.com/maps/api/geocode/json?latlng=$lat,$lng&key=$GOOGLE_API_KEY');
    final response  = await http.get(url);
    return json.decode(response.body)['results'][0]['formatted_address'];
    //might find multiple addresses, ordered by relevance, therefore [0]
  }
}

